package com.zentaritas.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Drops the stale room_bookings_status_check constraint at startup.
 * The constraint was auto-generated by Hibernate before ATTENDED / NO_SHOW
 * were added to BookingStatus, so it rejects those values.
 * After dropping, all enum values work and Hibernate will not recreate the constraint.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class BookingSchemaFixRunner implements ApplicationRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(ApplicationArguments args) {
        try {
            jdbcTemplate.execute(
                "ALTER TABLE room_bookings DROP CONSTRAINT IF EXISTS room_bookings_status_check"
            );
            log.info("Dropped stale room_bookings_status_check constraint");
        } catch (Exception e) {
            log.warn("Could not drop room_bookings_status_check (may not exist): {}", e.getMessage());
        }
    }
}
